language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile.activemodel-3.0
  - gemfiles/Gemfile.activemodel-4.0
notifications:
  email: false
script: bundle exec rspec spec
